### ISSUE TITLE
IPv6 in applicance_console -- tracking status

### ISSUE THREAD

**Issue by isimluk** [ManageIQ/manageiq-gems-pending#72]
## appliance_console
- [x] First status page (should show IPv6)
- [x] Network set-up
  - [x] Static IPv6
  - [x] DHCPv6
  - [x] Test network set up (ping IPv6)
- [x] Restore Database From Backup
  - [x] nfs (over IPv6)
  - [x] smb (over IPv6, didn't test but should just work, sharing the code with nfs)
- [x] Database Configuration
  - [x] Fetch Key (over IPv6)
  - [x] Join Region in External Database
  - [x] Create Region in External Database
- [x] Configure Database Replication
  - [x] Configure Server as Primary (allows inputs of IPv6, didn't check if the set-up works)
  - [x] Configure Server as Standby (allows inputs of IPv6, didn't check if the set-up works)
- [x] Generate Custom Encryption Key
   - [x] Fetch Key (over IPv6)
  
## Other extra commands
- [x] rake evm:db:backup:remote -- --uri nfs://[2620:52:0:2804:3fec:900f:ca31:a115]/export/backup --remote-file-name myfile

## Other features
- [x] An IPv6-only appliance (without db) successfully connect to another (IPv6-only) appliance with db
- [x] An IPv6-only appliance (represents region 1) successfully replicates to master region (IPv6-only)

**Comment by isimluk** [comment]
Configuration of remote database over ipv6 works.
```
Activating the configuration using the following settings...
Host:     2620:52:0:1007:21a:4eff:fe16:198
Username: root
Database: vmdb_production
Port:     5432


Configuration activated successfully.

Press any key to continue.
```
yax!
